FROM golang:1.25.4-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.20

WORKDIR /migrations
COPY --from=builder /go/bin/goose /usr/local/bin/goose

COPY app/migrations /migrations
COPY ./run-migrations.sh /usr/local/bin/run-migrations.sh
RUN chmod +x /usr/local/bin/run-migrations.sh

CMD ["/usr/local/bin/run-migrations.sh"]